name: Despliegue Continuo

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el código
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v2

      - name: Subir archivos del sitio
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

      - name: Desplegar a GitHub Pages
        uses: actions/deploy-pages@v1
