name: Integración Continua

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar linters
        run: |
          npm install -g htmlhint stylelint

      - name: Verificar HTML
        run: htmlhint "**/*.html"

      - name: Verificar CSS
        run: stylelint "**/*.css"
