name: Despliegue Continuo

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Subir archivos del sitio
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Cambia si tienes /dist o /build

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
