name: Despliegue Continuo

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v2

      - name: Subir archivos para deploy
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'  # Asegúrate que tu index.html esté en la raíz o ajusta la ruta

      - name: Desplegar
        id: deployment
        uses: actions/deploy-pages@v1
