name: Integración Continua

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Verificar estructura del proyecto
        run: echo "Verificando que el código se subió correctamente"
